name: CreeperGuard
version: 1.0
description: Prevents creeper explosions from destroying blocks
author: karlsson1000
api-version: 1.21
main: org.karlssonsmp.creeperGuard.CreeperGuard

commands:
  creeperguard:
    description: Toggle creeper protection
    aliases: [cg]
    permission: creeperguard.admin
    usage: /<command> [on|off]

permissions:
  creeperguard.admin:
    description: Allows toggling creeper protection
    default: op